---
- name: preparation
  hosts: 127.0.0.1
  connection: local
  roles:
    - kewlfft.aur
  tasks:
    - name: configure git
      include_role:
        name: git_config
    - name: clone & set dotfiles
      git:
        repo: "https://github.com/n0nvme/dotfiles"
        dest: "/home/n0nvme/.config"
    - name: install yay
      include_role:
        name: install_yay

- name: install packages
  hosts: 127.0.0.1
  connection: local
  roles:
    - kewlfft.aur
  tasks:
    - name: graphics installation
      loop:
        - xorg-server
        - xorg-xinit
        - xorg-xrandr
        - awesome-git
        - i3lock-color
      include_role:
        name: aur_install
    - name: set xinitrc
      copy:
        content: "exec awesome"
        dest: /home/n0nvme/.xinitrc
    - name: install & enable daemons # TODO: enable daemons
      loop:
        - networkmanager
        - docker
        - blueman
        - pulseaudio
      include_role:
        name: aur_install

    - name: install cli tools
      loop:
        - dialog
        - fish
        - openssh
        - freerdp
        - mc
        - ponysay
        - htop
        - gotop-bin
        - vim
        - zip
        - unzip
        - docker-compose
        - mitmproxy
        - samba
      include_role:
        name: aur_install

    - name: fonts installation
      loop:
        - noto-fonts
        - noto-fonts-emoji
        - nerd-fonts-terminus
        - nerd-fonts-source-code-pro
      include_role:
        name: aur_install

    - name: install gui tools
      loop:
        - slack-desktop
        - telegram-desktop-bin
        - google-chrome
        - visual-studio-code-insiders
        - alacritty
        - robo3t-bin
        - mongodb-compass
        - dbeaver
        - notion-app
        - flameshot
        - libreoffice-fresh
        - doublecmd-qt5
      include_role:
        name: aur_install

# - name: install omf
#   hosts: 127.0.0.1
#   connection: local
#   tasks:
#     - name: install
#       command: curl -L https://get.oh-my.fish | fish

- name: install python packages
  hosts: 127.0.0.1
  connection: local
  roles:
    - role: markosamuli.pyenv
      pyenv_python_versions:
        - 3.6.6
      pyenv_global: 3.6.6
  tasks:
    - name: install python tools
      loop:
        - bumpversion
        - poetry
      pip:
        name: "{{ item }}"
