---
- name: prepare
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tasks:
    - name: configure git
      ansible.builtin.copy:
        content: |
          [user]
              email = svmpl3nvm3@gmail.com
              name = n0nvme
        dest: /home/n0nvme/.gitconfig
        mode: 0644
    - name: install yay
      kewlfft.aur.aur:
        name: yay
        state: present
        use: makepkg
- name: awesomewm
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tags:
    - never
    - awesomewm
  tasks:
    - name: awesomewm config
      ansible.builtin.git:
        repo: https://github.com/n0nvme/s1mpl3.git
        dest: /home/n0nvme/.config/awesome
    - name: awesomewm nice
      ansible.builtin.git:
        repo: https://github.com/mut-ex/awesome-wm-nice.git
        dest: /home/n0nvme/.config/awesome/nice
    - name: awesomewm awesome-wm-widgets
      ansible.builtin.git:
        repo: https://github.com/streetturtle/awesome-wm-widgets.git
        dest: /home/n0nvme/.config/awesome/awesome-wm-widgets
- name: other files
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tasks:
    - name: set xinitrc
      ansible.builtin.copy:
        content: |
          picom -b --unredir-if-possible --backend glx --vsync --glx-no-stencil &
          export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
          onboard &
          nm-applet &
          blueman-applet &
          flameshot &
          xbindkeys &
          exec awesome
        dest: /home/n0nvme/.xinitrc
        mode: 0644
    - name: edit pacman.conf
      ansible.builtin.blockinfile:
        path: /etc/pacman.conf
        block: |
          [options]
          ParallelDownloads = 5
          Color
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      become: true
      tags:
        - preheat
- name: setup rootless podman
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: setup subuid
      ansible.builtin.copy:
        content: |
          n0nvme:100000:65536
        dest: /etc/subuid
        mode: 0644
      become: true
    - name: setup subgid
      ansible.builtin.copy:
        content: |
          n0nvme:100000:65536
        dest: /etc/subgid
        mode: 0644
      become: true
- name: systemd magic
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  roles:
    - systemd
- name: reflector-config
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tags:
    - reflector
    - preheat
  tasks:
    - name: install package
      ansible.builtin.pacman:
        state: present
        name:
          - reflector
      become: true
    - name: configure reflector
      ansible.builtin.copy:
        content: |
          --save /etc/pacman.d/mirrorlist
          --country Russia,Finland,Netherlands
          --protocol https
          --sort rate
          --latest 10
        dest: /etc/xdg/reflector/reflector.conf
        mode: 0644
      become: true
- name: xbindkeys
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  roles:
    - xbindkeys
- name: change user shell to zsh
  hosts: 127.0.0.1
  become: true
  tasks:
    - ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
