---
- name: prepare
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: configure git
      include_role:
        name: git_config
    - name: install yay
      kewlfft.aur.aur:
        name: yay
        state: present
        use: makepkg

- name: clone dotfiles
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: kitty config # noqa: git-latest
      git:
        repo: https://github.com/n0nvme/kitty-config.git
        dest: /home/n0nvme/.config/kitty

- name: install packages
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: graphics installation
      loop:
        - xorg-server
        - xorg-xinit
        - xorg-xrandr
        - awesome-git
        - i3lock-color
        - picom-git
      include_role:
        name: aur_install
    - name: set xinitrc
      copy:
        content: "picom -b --unredir-if-possible --backend glx --vsync --glx-no-stencil &\nexec awesome"
        dest: /home/n0nvme/.xinitrc
    - name: install & enable daemons # TODO: enable daemons
      loop:
        - networkmanager
        - docker
        - blueman
        - pulseaudio
      include_role:
        name: aur_install

    - name: install cli tools
      loop:
        - dialog
        - zsh
        - openssh
        - freerdp
        - openvpn
        - mc
        - htop
        - vim
        - zip
        - unzip
        - tar
        - docker-compose
        - mitmproxy
        - samba
        - smartmontools
        - kubectl
        - kubectx
        - kubecolor
      include_role:
        name: aur_install

    - name: fonts installation
      loop:
        - noto-fonts
        - noto-fonts-emoji
        - nerd-fonts-terminus
        - nerd-fonts-source-code-pro
      include_role:
        name: aur_install

    - name: install gui tools
      loop:
        - slack-desktop
        - telegram-desktop-bin
        - google-chrome
        - spotify
        - visual-studio-code-insiders-bin
        - kitty
        - robo3t-bin
        - dbeaver
        - notion-app
        - flameshot
        - libreoffice-fresh
        - doublecmd-qt5
        - keepassxc
        - obsidian
      include_role:
        name: aur_install

- name: install python packages
  hosts: 127.0.0.1
  connection: local
  roles:
    - role: markosamuli.pyenv
      pyenv_python_versions:
        - 3.6.6
        - 3.8.2
        - 3.10.0
      pyenv_global: system
  tasks:
    - name: install python tools
      loop:
        - bumpversion
        - poetry
      pip:
        name: "{{ item }}"
