---
- name: prepare
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tasks:
    - name: configure git
      copy:
        content: |
          [user]
              email = svmpl3nvm3@gmail.com
              name = n0nvme
        dest: /home/n0nvme/.gitconfig
        mode: 0644
    - name: install yay
      kewlfft.aur.aur:
        name: yay
        state: present
        use: makepkg
- name: dotfiles
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tasks:
    - name: kitty config
      git:
        repo: https://github.com/n0nvme/kitty-config.git
        dest: /home/n0nvme/.config/kitty
    - name: zshenv
      copy:
        content: "ZDOTDIR=~/.config/zsh"
        dest: /home/n0nvme/.zshenv
        mode: 0644
    - name: zsh config
      git:
        repo: https://github.com/n0nvme/zshrc.git
        dest: /home/n0nvme/.config/zsh
- name: other files
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tasks:
    - name: set xinitrc
      copy:
        content: |
          picom -b --unredir-if-possible --backend glx --vsync --glx-no-stencil &
          eval $(gnome-keyring-daemon --start)
          export SSH_AUTH_SOCK
          onboard &
          nm-applet &
          blueman-applet &
          flameshot &
          exec awesome
        dest: /home/n0nvme/.xinitrc
        mode: 0644
    - name: set pam.d/login
      copy:
        content: |
          auth       required     pam_securetty.so
          auth       requisite    pam_nologin.so
          auth       include      system-local-login
          auth       optional     pam_gnome_keyring.so
          account    include      system-local-login
          session    include      system-local-login
          session    optional     pam_gnome_keyring.so auto_start
        dest: /etc/pam.d/login
        mode: 0644
      become: true
    - name: edit pacman.conf
      blockinfile:
        path: /etc/pacman.conf
        block: |
          [options]
          ParallelDownloads = 5
          Color
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      become: true
      tags:
        - preheat
    - name: fill libinput gestures config
      copy:
        content: |
          gesture swipe left xdotool key super+Left
          gesture swipe right xdotool key super+Right
        dest: /home/n0nvme/.config/libinput-gestures.conf
        mode: 0644
- name: install packages
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tasks:
    - name: read packages list
      include_vars:
        file: vars.yml
        name: packages
    - name: show packages
      ansible.builtin.debug: var=packages
      tags: [debug, never]
    - name: official packages
      ansible.builtin.pacman:
        state: present
        name: "{{ packages.pacman }}"
      become: true
    - name: aur packages
      kewlfft.aur.aur:
        state: present
        name: "{{ packages.aur }}"
- name: setup rootless podman
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: setup subuid
      copy:
        content: |
          n0nvme:100000:65536
        dest: /etc/subuid
        mode: 0644
      become: true
    - name: setup subgid
      copy:
        content: |
          n0nvme:100000:65536
        dest: /etc/subgid
        mode: 0644
      become: true
- name: install python packages
  hosts: 127.0.0.1
  connection: local
  roles:
    - role: markosamuli.pyenv
      environment:
        CC: clang
      pyenv_init_shell: false
      pyenv_python_versions:
        - 3.6.6
        - 3.8.2
        - 3.10.0
      pyenv_global: system
      pyenv_version: "v2.2.2"
- name: systemd magick
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  roles:
    - systemd
- name: reflector-config
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tags:
    - reflector
    - preheat
  tasks:
    - name: install package
      ansible.builtin.pacman:
        state: present
        name:
          - reflector
      become: true
    - name: configure reflector
      copy:
        content: |
          --save /etc/pacman.d/mirrorlist
          --country Russia,Finland,Netherlands
          --protocol https
          --sort rate
          --latest 10
        dest: /etc/xdg/reflector/reflector.conf
        mode: 0644
      become: true
