---
- name: prepare
  hosts: 127.0.0.1
  gather_facts: no
  connection: local
  tasks:
    - name: configure git
      copy:
        content: |
          [user]
              email = svmpl3nvm3@gmail.com
              name = n0nvme
        dest: /home/n0nvme/.gitconfig
        mode: 0644
    - name: install yay
      kewlfft.aur.aur:
        name: yay
        state: present
        use: makepkg
- name: dotfiles
  hosts: 127.0.0.1
  gather_facts: no
  connection: local
  tasks:
    - name: kitty config
      git:
        repo: git@github.com:n0nvme/kitty-config.git
        dest: /home/n0nvme/.config/kitty
    - name: zshenv
      copy:
        content: "ZDOTDIR=~/.config/zsh"
        dest: /home/n0nvme/.zshenv
        mode: 0644
    - name: zsh config
      git:
        repo: git@github.com:n0nvme/zshrc.git
        dest: /home/n0nvme/.config/zsh

- name: other files
  hosts: 127.0.0.1
  gather_facts: no
  connection: local
  tasks:
    - name: set xinitrc
      copy:
        content: |
          picom -b --unredir-if-possible --backend glx --vsync --glx-no-stencil &
          eval $(gnome-keyring-daemon --start)
          export SSH_AUTH_SOCK
          exec awesome
        dest: /home/n0nvme/.xinitrc
        mode: 0644
    - name: set pam.d/login
      copy:
        content: |
          auth       required     pam_securetty.so
          auth       requisite    pam_nologin.so
          auth       include      system-local-login
          auth       optional     pam_gnome_keyring.so
          account    include      system-local-login
          session    include      system-local-login
          session    optional     pam_gnome_keyring.so auto_start
        dest: /etc/pam.d/login
        mode: 0644
      become: yes
    - name: edit pacman.conf
      blockinfile:
        path: /etc/pacman.conf
        block: |
          ParallelDownloads = 5
          [options]
          Color
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

      become: yes
    - name: fill libinput gestures config
      copy:
        content: |
          gesture swipe left xdotool key super+Left
          gesture swipe right xdotool key super+Right
        dest: /home/n0nvme/.config/libinput-gestures.conf
        mode: 0644
- name: install packages
  hosts: 127.0.0.1
  gather_facts: no
  connection: local
  tasks:
    - name: graphics installation
      kewlfft.aur.aur:
        use: yay
        state: present
        name:
          - xorg-server
          - xorg-xinit
          - xorg-xrandr
          - awesome-git
          - i3lock-color
          - picom-git
    - name: install & enable daemons # TODO: enable daemons
      kewlfft.aur.aur:
        use: yay
        state: present
        name:
          - networkmanager
          - docker
          - blueman
          - pulseaudio
    - name: install other packages
      kewlfft.aur.aur:
        use: yay
        state: present
        name:
          - gnome-keyring
          - libsecret
          - wmctrl
          - xdotool
          - libinput-gestures
          - dex
    - name: install cli tools
      kewlfft.aur.aur:
        use: yay
        state: present
        name:
          - dialog
          - zsh
          - openssh
          - freerdp
          - openvpn
          - mc
          - htop
          - vim
          - clang
          - zip
          - unzip
          - tar
          - docker-compose
          - ansible-lint
          - mitmproxy
          - samba
          - smartmontools
          - kubectl
          - kubectx
          - kubecolor
          - exa
          - fzf
          - acpi
          - navi
          - curlie
    - name: fonts installation
      kewlfft.aur.aur:
        use: yay
        state: present
        name:
          - noto-fonts
          - noto-fonts-emoji
          - nerd-fonts-terminus
          - nerd-fonts-source-code-pro
          - ttf-fira-code
    - name: install gui tools
      kewlfft.aur.aur:
        use: yay
        state: present
        name:
          - slack-desktop
          - telegram-desktop
          - google-chrome
          - spotify
          - visual-studio-code-insiders-bin
          - kitty
          - robo3t-bin
          - dbeaver
          - notion-app
          - flameshot
          - libreoffice-fresh
          - doublecmd-qt5
          - keepassxc
          - obsidian
          - mailspring
- name: install && setup rootless podman
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - name: install podman with dependencies
      kewlfft.aur.aur:
        use: yay
        state: present
        name:
          - fuse-overlayfs
          - podman
    - name: setup subuid
      copy:
        content: |
          n0nvme:100000:65536
        dest: /etc/subuid
        mode: 0644
        become: yes
    - name: setup subgid
      copy:
        content: |
          n0nvme:100000:65536
        dest: /etc/subgid
        mode: 0644
        become: yes
- name: install python packages
  hosts: 127.0.0.1
  connection: local
  roles:
    - role: markosamuli.pyenv
      environment:
        CC: clang
      pyenv_init_shell: false
      pyenv_python_versions:
        - 3.6.6
        - 3.8.2
        - 3.10.0
      pyenv_global: system
      pyenv_version: "v2.2.2"
