---
- name: preparation
  hosts: 127.0.0.1
  connection: local
  roles:
    - kewlfft.aur
  tasks:
    - name: configure git
      include_role:
        name: git_config
    - name: clone & set dotfiles
      git:
        repo: "https://github.com/n0nvme/dotfiles"
        dest: "/home/n0nvme/.config"
    - name: install yay
      include_role:
        name: install_yay

- name: install packages
  hosts: 127.0.0.1
  connection: local
  roles:
    - kewlfft.aur
  tasks:
    - name: graphics installation
      loop:
        - awesome-git
      include_role:
        name: aur_install
    - name: set xinitrc
      copy:
        content: "exec awesome"
        dest: /home/n0nvme/.xinitrc
    - name: install & enable daemons # TODO: enable daemons
      loop:
        - networkmanager
        - docker
        - blueman
        - pulseaudio
      include_role:
        name: aur_install

    - name: install cli tools
      loop:
        - dialog
        - sensonrs
        - fish
        - oh-my-fish
        - mc
        - ponysay
        - htop
        - gotop-bin
        - vim
        - docker-compose
        - mitmproxy
      include_role:
        name: aur_install

    - name: fonts installation
      loop:
        - noto
        - noto-emoji
      include_role:
        name: aur_install

    - name: install gui tools
      loop:
        - slack
        - telegram-desktop-bin
        - google-chrome
        - code-insiders
        - alacritty
        - robo3t
        - mongodb-compass
        - dbeaver
        - notion-app
        - libreoffice
        - doublecmd-qt5
      include_role:
        name: aur_install

- name: install python packages
  hosts: 127.0.0.1
  connection: local
  roles:
    - role: markosamuli.pyenv
      pyenv_python_versions:
        - 3.6.6
      pyenv_global: 3.6.6
  tasks:
    - name: install python tools
      loop:
        - bumpversion
        - poetry
      pip:
        name: "{{ item }}"
