---
- name: prepare
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: configure git
      copy:
        content: |
          [user]
              email = svmpl3nvm3@gmail.com
              name = n0nvme
        dest: /home/n0nvme/.gitconfig
    - name: install yay
      kewlfft.aur.aur:
        name: yay
        state: present
        use: makepkg

- name: dotfiles
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: kitty config # noqa: git-latest
      git:
        repo: git@github.com:n0nvme/kitty-config.git
        dest: /home/n0nvme/.config/kitty
    - name: zshenv
      copy:
        content: "ZDOTDIR=~/.config/zsh"
        dest: /home/n0nvme/.zshenv
    - name: zsh config # noqa: git-latest
      git:
        repo: git@github.com:n0nvme/zshrc.git
        dest: /home/n0nvme/.config/zsh

- name: other files
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: set xinitrc
      copy:
        content: |
          picom -b --unredir-if-possible --backend glx --vsync --glx-no-stencil &
          eval $(gnome-keyring-daemon --start)
          export SSH_AUTH_SOCK
          exec awesome
        dest: /home/n0nvme/.xinitrc
    - name: set pam.d/login
      copy:
        content: |
          auth       required     pam_securetty.so
          auth       requisite    pam_nologin.so
          auth       include      system-local-login
          auth       optional     pam_gnome_keyring.so
          account    include      system-local-login
          session    include      system-local-login
          session    optional     pam_gnome_keyring.so auto_start
        dest: /etc/pam.d/login
      become: yes
    - name: enable pacman colors
      blockinfile:
        path: /etc/pacman.conf
        block: |
          [options]
          Color
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      become: yes
    - name: fill libinput gestures config
      copy:
        content: |
          gesture swipe left xdotool key super+Left
          gesture swipe right xdotool key super+Right
        dest: /home/n0nvme/.config/libinput-gestures.conf
- name: install packages
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: graphics installation
      loop:
        - xorg-server
        - xorg-xinit
        - xorg-xrandr
        - awesome-git
        - i3lock-color
        - picom-git
      include_role:
        name: aur_install
    - name: install & enable daemons # TODO: enable daemons
      loop:
        - networkmanager
        - docker
        - blueman
        - pulseaudio
      include_role:
        name: aur_install
    - name: install other packages
      loop:
        - gnome-keyring
        - libsecret
        - wmctrl
        - xdotool
        - libinput-gestures
        - dex
      include_role:
        name: aur_install
    - name: install cli tools
      loop:
        - dialog
        - zsh
        - openssh
        - freerdp
        - openvpn
        - mc
        - htop
        - vim
        - clang
        - zip
        - unzip
        - tar
        - docker-compose
        - ansible-lint
        - mitmproxy
        - samba
        - smartmontools
        - kubectl
        - kubectx
        - kubecolor
        - exa
        - fzf
        - acpi
        - navi
      include_role:
        name: aur_install

    - name: fonts installation
      loop:
        - noto-fonts
        - noto-fonts-emoji
        - nerd-fonts-terminus
        - nerd-fonts-source-code-pro
        - ttf-fira-code
      include_role:
        name: aur_install

    - name: install gui tools
      loop:
        - slack-desktop
        - telegram-desktop-bin
        - google-chrome
        - spotify
        - visual-studio-code-insiders-bin
        - kitty
        - robo3t-bin
        - dbeaver
        - notion-app
        - flameshot
        - libreoffice-fresh
        - doublecmd-qt5
        - keepassxc
        - obsidian
        - mailspring
      include_role:
        name: aur_install

- name: install python packages
  hosts: 127.0.0.1
  connection: local
  roles:
    - role: markosamuli.pyenv
      environment:
        CC: clang
      pyenv_python_versions:
        - 3.6.6
        - 3.8.2
        - 3.10.0
      pyenv_global: system
      pyenv_version: "v2.2.2"