- name: copy suspend service
  ansible.builtin.copy:
    src: suspend@.service
    dest: /etc/systemd/system/suspend@.service
    mode: 0644
  become: true
- name: enable suspend service
  ansible.builtin.systemd:
    enabled: true
    name: suspend@n0nvme
  become: true
- name: Ensure .config/systemd/user/ dir exists
  ansible.builtin.file: path=/home/n0nvme/config/systemd/user/ state=directory mode=0644
- name: copy ssh-agent service
  ansible.builtin.copy:
    src: ssh-agent.service
    dest: /home/n0nvme/.config/systemd/user/ssh-agent.service
    mode: 0644
- name: enable suspend service
  ansible.builtin.systemd:
    enabled: true
    name: ssh-agent
    scope: user
