- name: copy suspend service
  copy:
    src: suspend@.service
    dest: /etc/systemd/system/suspend@.service
    mode: 0644
  become: true
- name: enable suspend service
  ansible.builtin.systemd:
    enabled: true
    name: suspend@n0nvme
  become: true
- name: copy ssh-agent service
  copy:
    src: ssh-agent.service
    dest: /etc/systemd/system/ssh-agent.servicee
    mode: 0644
  become: true
- name: enable suspend service
  ansible.builtin.systemd:
    enabled: true
    name: ssh-agent
    scope: user
