- name: copy suspend service
  ansible.builtin.copy:
    src: suspend@.service
    dest: /etc/systemd/system/suspend@.service
    mode: 0644
  become: true
- name: enable suspend service
  ansible.builtin.systemd:
    enabled: true
    name: suspend@n0nvme
  become: true
- name: Ensure .config/systemd/user/ dir exists
  ansible.builtin.file: path=/home/n0nvme/config/systemd/user/ state=directory mode=0755
- name: copy ssh-agent service
  ansible.builtin.copy:
    src: ssh-agent.service
    dest: /home/n0nvme/.config/systemd/user/ssh-agent.service
    mode: 0644
- name: enable ssh-agent service
  ansible.builtin.systemd:
    enabled: true
    name: ssh-agent
    scope: user
- name: copy avizo service
  ansible.builtin.copy:
    src: avizo.service
    dest: /home/n0nvme/.config/systemd/user/avizo.service
    mode: 0644
- name: copy hyprland target
  ansible.builtin.copy:
    src: hyprland-session.target
    dest: /home/n0nvme/.config/systemd/user/hyprland-session.target
    mode: 0644
- name: enable avizo service
  ansible.builtin.systemd:
    enabled: true
    name: avizo
    scope: user
- name: enable waybar service
  ansible.builtin.systemd:
    enabled: true
    name: waybar
    scope: user
- name: enable swaync service
  ansible.builtin.systemd:
    enabled: true
    name: swaync
    scope: user
