name: Ansible Lint  # feel free to pick your own name

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install asnible-lint
      - run: asnible-lint site.yml
